name: Lint Charts
on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    branches:
     - master
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Helm Lint
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: "lint ./cronjob/"
      - name: Helm template
        id: template
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: "template cronjob ./cronjob"
      - name: Helm Package
        uses: Flydiverny/helm-package-action@0.1.0
        with:
          args: "./cronjob -d ./stable"
